### ISSUE TITLE
Dragonite Admin defaults to port 9003

### ISSUE THREAD

**Issue by clburlison** [UnownHash/Dragonite-Public#7]
Please make Dragonite Admin default to port `7273` instead of port 9003. This will make the setup cleaner for docker and more consistent with the rest of the project.

```
root@server:~/unownhash# docker compose logs -f admin
admin  | INFO 2023-11-13 00:47:46 Starting Dragonite-Admin Public 1.1.0
admin  | INFO 2023-11-13 00:47:46 Listening on 0.0.0.0:9003
```

Bandaid until a patch is released

```
  admin:
    image: ghcr.io/unownhash/dragonite-public-admin:latest
    container_name: admin
    restart: unless-stopped
    environment:
      ADMIN_GENERAL_HOST: 0.0.0.0
      ADMIN_GENERAL_USERNAME: admin
      ADMIN_GENERAL_PASSWORD: password
      ADMIN_DRAGONITE_API_ENDPOINT: http://dragonite:7272
      ADMIN_DRAGONITE_API_SECRET: ""
      ADMIN_GOLBAT_API_ENDPOINT: http://golbat:9001
      ADMIN_GOLBAT_API_SECRET: ""
    ports:
      #- '7273:7273'
      - '7273:9003'
```
